#!/usr/bin/env python3
"""Freeze the main paper's label numbers into tex/main-refs.tex.

The supplement cross-references sections and equations of the main paper.
The xr package does this by reading main.aux at compile time, which fails on
Overleaf: each root document builds in its own sandbox, so main.aux is never
visible when supplement.tex compiles, and every cross-document reference
renders as "??". Instead, the supplement \\input's main-refs.tex -- a
generated file containing exactly the \\newlabel lines it needs -- and
therefore compiles standalone anywhere, in any order.

The price is staleness: if the main paper is renumbered, the frozen numbers
are silently wrong until this script is re-run. Two mitigations: the script
refuses to write if a referenced label no longer exists in main.aux, and it
prints a diff of numbers that changed so a renumbering is visible rather
than silent.

Usage (from tex/, after compiling main.tex so main.aux is current)::

    python make_supplement_refs.py
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent

HEADER = """% main-refs.tex -- label numbers of the MAIN paper, frozen for the
% supplement's cross-references.
%
% GENERATED by make_supplement_refs.py from main.aux -- do not edit by hand.
% Regenerate whenever the main paper's numbering changes:
%   pdflatex main.tex && python make_supplement_refs.py
"""


def main() -> int:
    supp = (HERE / "supplement.tex").read_text(encoding="utf-8")
    refs = set(re.findall(r"\\(?:ref|eqref)\{([^}]+)\}", supp))
    own = set(re.findall(r"\\label\{([^}]+)\}", supp))
    external = sorted(refs - own)

    aux_path = HERE / "main.aux"
    if not aux_path.exists():
        print("main.aux not found -- compile main.tex first.")
        return 1
    aux = aux_path.read_text(encoding="utf-8")

    lines, missing = [], []
    for lab in external:
        m = re.search(r"\\newlabel\{" + re.escape(lab) + r"\}\{.*\}", aux)
        (lines if m else missing).append(m.group(0) if m else lab)

    if missing:
        print("REFUSING to write: these labels are referenced by the "
              "supplement but no longer exist in main.aux:")
        for lab in missing:
            print("  ", lab)
        return 1

    out_path = HERE / "main-refs.tex"
    new = HEADER + "\n".join(lines) + "\n"
    if out_path.exists():
        old = out_path.read_text(encoding="utf-8")
        changed = [l for l in lines if l not in old]
        if changed:
            print("Numbering changed for:")
            for l in changed:
                print("  ", l)
    out_path.write_text(new, encoding="utf-8")
    print(f"main-refs.tex: {len(lines)} labels frozen.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
